import type { NextPage, NextPageContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../components/Layout'

export type Props = {
  isLoggedIn: boolean;
};

export const getServerSideProps = async (ctx: NextPageContext): Promise<{ props: Props }> => {
  const res = await fetch('https://api.ammonite-profiler.xyz/GetUser', {
    headers: {
      Cookie: ctx.req?.headers.cookie ?? ''
    }
  })
  return {
    props: {
      isLoggedIn: res.status == 200
    }
  }
}

const Home: NextPage<Props> = (props: Props) => {
  return (
    <Layout title="Profile">
    <div className={styles.container}>
      <Head>
        <title>ammonite-profiler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ammonite-profiler
        </h1>

        <p className={styles.description}>
          find the sourcecode
          <Link href="https://github.com/pdettmann/ammonite-profiler">
            <a> here</a>
          </Link>
        </p>
        <div>
            {
              props.isLoggedIn ? <Link href="/profile" aria-label="Link to profile page">Profile</Link> : <Link href="https://api.ammonite-profiler.xyz/Login" aria-label="Link to login page" role="link">Log In/Sign Up</Link>
            }
        </div >

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </Layout>
  )
}

export default Home
